apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: skynet
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: postgres
      managed: true
      overrides:
        storageClassName: local-path
    - kind: clairpostgres
      managed: true
      overrides:
        storageClassName: local-path